### ISSUE TITLE
Resume link uses import path instead of public url

### ISSUE THREAD

**Issue by gtangelo** [Darianlmj/Darianlmj#44]
Hey! I was going through your portfolio website and I must say, it is a very cool and well designed portfolio website! You seemed to have the development skills of a frontend god! You should take pride in the skillset you have and I'm sure you'll do wonders with your career going forward :D.

Just creating an issue as I seemed to notice that when viewing your resume, it seems to redirect me with the import path in the code over the public url that is hosting your resume file. Again, this is a minor bug and probably got overlooked which is fair. But anyways, your skillset should be really valued from what I've seen. :))

Hope the future goes well for you! 😎 

![image](https://user-images.githubusercontent.com/65492346/234278703-4ba38a4c-4870-44bc-9233-2f7ac6185f77.png)

**Comment by Darianlmj** [comment]
Hey @gtangelo,

Thanks for the kind words 🥰. Really appreciate it. Also thanks for opening this issue, I have made a fix for it so hopefully your user experience will be much better now 😎
